export {default as Navbar} from './Navbars/Navbar'
export {default as Banner} from './banner-section/banner'
export {default as Client} from './client-section/Client'
export {default as Feature} from './feature-section/Feature'
export {default as About} from './about-section/About'
export {default as Process} from './proceess-section/Process'
export {default as Test} from './testimonial-section/Test'
export {default as Team} from './team-section/Team'
export { default as Agent} from './agent-section/Agent'
export {default as Switcher} from './switcher/Switcher'
export {default as Scroll} from './scroll/Scroll'